### ISSUE TITLE
nanosound20171013.zip contains source code, version it with git

### ISSUE THREAD

**Issue by arthurlutz** [nanomesher/Nanomesher_NanoSound#6]
I was about to contribute a change to index.js and realized it was in a zip under git. Maybe this should be directly in the git so changes can be tracked in a more easier fashion ?

**Comment by nanomesher** [comment]
@arthurlutz  ,  the nanosound volumio plug in is under is [here](https://github.com/nanomesher/volumio-plugins/tree/master/plugins/miscellanea/nanosound), you are free to contribute

thanks
